language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - 8.2

matrix:
  include:
    - php: 7.1
      env: dependencies=lowest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

before_script:
  - travis_retry composer install --no-interaction
  - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - .build/bin/phpspec run
  - .build/bin/behat -fprogress
